server:
  error:
    include-message: always
  port: 80

spring:
  application:
    name: health-mate
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect
        highlight_sql: false

security:
  jwt:
    secret: ${JWT_SECRET}
    access-validity-ms: 3600000
